[2025-07-24T17:31:38.900+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_full_etl_dag.stage_events manual__2025-07-24T17:31:31.521359+00:00 [queued]>
[2025-07-24T17:31:38.916+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_full_etl_dag.stage_events manual__2025-07-24T17:31:31.521359+00:00 [queued]>
[2025-07-24T17:31:38.917+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4
[2025-07-24T17:31:38.940+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): stage_events> on 2025-07-24 17:31:31.521359+00:00
[2025-07-24T17:31:38.951+0000] {standard_task_runner.py:60} INFO - Started process 797 to run task
[2025-07-24T17:31:38.985+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'tunestream_full_etl_dag', 'stage_events', 'manual__2025-07-24T17:31:31.521359+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/step12345.py', '--cfg-path', '/tmp/tmp2b3j27gi']
[2025-07-24T17:31:39.036+0000] {standard_task_runner.py:88} INFO - Job 49: Subtask stage_events
[2025-07-24T17:31:40.303+0000] {task_command.py:423} INFO - Running <TaskInstance: tunestream_full_etl_dag.stage_events manual__2025-07-24T17:31:31.521359+00:00 [running]> on host 737498b59352
[2025-07-24T17:31:40.844+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tunestream_full_etl_dag' AIRFLOW_CTX_TASK_ID='stage_events' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T17:31:31.521359+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T17:31:31.521359+00:00'
[2025-07-24T17:31:40.904+0000] {base.py:83} INFO - Using connection ID 'postgres_local' for task execution.
[2025-07-24T17:31:41.167+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/step12345.py", line 150, in stage_events_task
    json_to_sql("postgres_local","staging_events",LOG_DATA_PATH,event_columns)
  File "/opt/airflow/dags/step12345.py", line 73, in json_to_sql
    conn = postgres_hook.get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-07-24T17:31:41.228+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_full_etl_dag, task_id=stage_events, execution_date=20250724T173131, start_date=20250724T173138, end_date=20250724T173141
[2025-07-24T17:31:41.260+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 49 for task stage_events (connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 797)
[2025-07-24T17:31:41.290+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-24T17:31:41.334+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
